services:
  - type: web
    name: projeto-yf-api
    runtime: docker
    plan: standard
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: neondb
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          name: projeto-yf-api
          type: web
          property: renderUrl
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_PRESET
        sync: false
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /
    numInstances: 1

databases:
  - name: neondb
    plan: standard
